/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface _SERVICE {
  'getAbout' : ActorMethod<[], string>,
  'getCertifications' : ActorMethod<[], string>,
  'getContact' : ActorMethod<[], string>,
  'getEducation' : ActorMethod<[], string>,
  'getExperience' : ActorMethod<[], string>,
  'getHero' : ActorMethod<[], string>,
  'getProjects' : ActorMethod<[], string>,
  'getSkills' : ActorMethod<[], string>,
  'updateAbout' : ActorMethod<[string], undefined>,
  'updateCertifications' : ActorMethod<[string], undefined>,
  'updateContact' : ActorMethod<[string], undefined>,
  'updateEducation' : ActorMethod<[string], undefined>,
  'updateExperience' : ActorMethod<[string], undefined>,
  'updateHero' : ActorMethod<[string], undefined>,
  'updateProjects' : ActorMethod<[string], undefined>,
  'updateSkills' : ActorMethod<[string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];