/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const idlService = IDL.Service({
  'getAbout' : IDL.Func([], [IDL.Text], ['query']),
  'getCertifications' : IDL.Func([], [IDL.Text], ['query']),
  'getContact' : IDL.Func([], [IDL.Text], ['query']),
  'getEducation' : IDL.Func([], [IDL.Text], ['query']),
  'getExperience' : IDL.Func([], [IDL.Text], ['query']),
  'getHero' : IDL.Func([], [IDL.Text], ['query']),
  'getProjects' : IDL.Func([], [IDL.Text], ['query']),
  'getSkills' : IDL.Func([], [IDL.Text], ['query']),
  'updateAbout' : IDL.Func([IDL.Text], [], []),
  'updateCertifications' : IDL.Func([IDL.Text], [], []),
  'updateContact' : IDL.Func([IDL.Text], [], []),
  'updateEducation' : IDL.Func([IDL.Text], [], []),
  'updateExperience' : IDL.Func([IDL.Text], [], []),
  'updateHero' : IDL.Func([IDL.Text], [], []),
  'updateProjects' : IDL.Func([IDL.Text], [], []),
  'updateSkills' : IDL.Func([IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  return IDL.Service({
    'getAbout' : IDL.Func([], [IDL.Text], ['query']),
    'getCertifications' : IDL.Func([], [IDL.Text], ['query']),
    'getContact' : IDL.Func([], [IDL.Text], ['query']),
    'getEducation' : IDL.Func([], [IDL.Text], ['query']),
    'getExperience' : IDL.Func([], [IDL.Text], ['query']),
    'getHero' : IDL.Func([], [IDL.Text], ['query']),
    'getProjects' : IDL.Func([], [IDL.Text], ['query']),
    'getSkills' : IDL.Func([], [IDL.Text], ['query']),
    'updateAbout' : IDL.Func([IDL.Text], [], []),
    'updateCertifications' : IDL.Func([IDL.Text], [], []),
    'updateContact' : IDL.Func([IDL.Text], [], []),
    'updateEducation' : IDL.Func([IDL.Text], [], []),
    'updateExperience' : IDL.Func([IDL.Text], [], []),
    'updateHero' : IDL.Func([IDL.Text], [], []),
    'updateProjects' : IDL.Func([IDL.Text], [], []),
    'updateSkills' : IDL.Func([IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };